//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmBracketDesignLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArmBracketDesignLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;BktThickness&quot;: &quot;0.500&quot;,
        ///		&quot;BendRadius&quot;: &quot;1.000&quot;
        ///	},
        ///	{
        ///		&quot;BktThickness&quot;: &quot;0.625&quot;,
        ///		&quot;BendRadius&quot;: &quot;1.875&quot;
        ///	},
        ///	{
        ///		&quot;BktThickness&quot;: &quot;0.750&quot;,
        ///		&quot;BendRadius&quot;: &quot;2.250&quot;
        ///	},
        ///	{
        ///		&quot;BktThickness&quot;: &quot;0.875&quot;,
        ///		&quot;BendRadius&quot;: &quot;2.625&quot;
        ///	},
        ///	{
        ///		&quot;BktThickness&quot;: &quot;1.000&quot;,
        ///		&quot;BendRadius&quot;: &quot;3.000&quot;
        ///	},
        ///	{
        ///		&quot;BktThickness&quot;: &quot;1.250&quot;,
        ///		&quot;BendRadius&quot;: &quot;3.750&quot;
        ///	}
        ///].
        /// </summary>
        internal static string BracketBendRadii_json {
            get {
                return ResourceManager.GetString("BracketBendRadii_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;BoltSpec&quot;:&quot;A193-B7&quot;,
        ///    &quot;FY_1&quot;:105,
        ///    &quot;FY_2&quot;:95,
        ///    &quot;FY_3&quot;:0,
        ///    &quot;FU_1&quot;:125,
        ///    &quot;FU_2&quot;:115,
        ///    &quot;FU_3&quot;:0,
        ///},
        ///{
        ///    &quot;BoltSpec&quot;:&quot;A325&quot;,
        ///    &quot;FY_1&quot;:92,
        ///    &quot;FY_2&quot;:81,
        ///    &quot;FY_3&quot;:0,
        ///    &quot;FU_1&quot;:120,
        ///    &quot;FU_2&quot;:105,
        ///    &quot;FU_3&quot;:0,
        ///},
        ///{
        ///    &quot;BoltSpec&quot;:&quot;A354-BC&quot;,
        ///    &quot;FY_1&quot;:109,
        ///    &quot;FY_2&quot;:94,
        ///    &quot;FY_3&quot;:0,
        ///    &quot;FU_1&quot;:125,
        ///    &quot;FU_2&quot;:115,
        ///    &quot;FU_3&quot;:0,
        ///},
        ///{
        ///    &quot;BoltSpec&quot;:&quot;A354-BD&quot;,
        ///    &quot;FY_1&quot;:130,
        ///    &quot;FY_2&quot;:115,
        ///    &quot;FY_3&quot;:0,
        ///    &quot;FU_1&quot;:150,
        ///    &quot;FU_2&quot;:140,
        ///    &quot;FU_3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BracketBoltGrade_json {
            get {
                return ResourceManager.GetString("BracketBoltGrade_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;ArmWallThick&quot;:0.1875,
        ///    &quot;Threshold&quot;:17,
        ///    &quot;PJP_1&quot;:0.375,
        ///    &quot;PJP_2&quot;:0.3125,
        ///    &quot;CJP&quot;:0.1875,
        ///},
        ///{
        ///    &quot;ArmWallThick&quot;:0.25,
        ///    &quot;Threshold&quot;:25,
        ///    &quot;PJP_1&quot;:0.4375,
        ///    &quot;PJP_2&quot;:0.375,
        ///    &quot;CJP&quot;:0.25,
        ///},
        ///{
        ///    &quot;ArmWallThick&quot;:0.3125,
        ///    &quot;Threshold&quot;:30,
        ///    &quot;PJP_1&quot;:0.5625,
        ///    &quot;PJP_2&quot;:0.5,
        ///    &quot;CJP&quot;:0.3125,
        ///},
        ///{
        ///    &quot;ArmWallThick&quot;:0.375,
        ///    &quot;Threshold&quot;:34,
        ///    &quot;PJP_1&quot;:0.6875,
        ///    &quot;PJP_2&quot;:0.625,
        ///    &quot;CJP&quot;:0.3125,
        ///},
        ///{
        ///    &quot;ArmWallThick&quot;:0.4375,
        ///    &quot;Threshold&quot;:43,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BracketToArmWeldSize_json {
            get {
                return ResourceManager.GetString("BracketToArmWeldSize_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ShaftID&quot;: 2,
        ///    &quot;XSectArea&quot;: 3.31,
        ///    &quot;CenterCutoutDia&quot;: 1.25,
        ///    &quot;DrainHoleDia&quot;: 0,
        ///    &quot;DrainHoleQty&quot;: 0,
        ///    &quot;DrainHoleDist&quot;: 0,
        ///    &quot;CutoutArea&quot;: 1.23,
        ///    &quot;PercentXSectArea&quot;: 37.03,
        ///    &quot;CutoutType&quot;: &quot;A&quot;,
        ///    &quot;PartNumber&quot;: &quot;A01Q00000&quot;
        ///  },
        ///  {
        ///    &quot;ShaftID&quot;: 3,
        ///    &quot;XSectArea&quot;: 7.46,
        ///    &quot;CenterCutoutDia&quot;: 2.25,
        ///    &quot;DrainHoleDia&quot;: 0,
        ///    &quot;DrainHoleQty&quot;: 0,
        ///    &quot;DrainHoleDist&quot;: 0,
        ///    &quot;CutoutArea&quot;: 3.98,
        ///    &quot;PercentXSectArea&quot;: 53.33,
        ///    &quot;CutoutType&quot;: &quot;A&quot;,
        ///    &quot;PartNumber&quot;: &quot;A02Q00000&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SabreCustomBrackets_json {
            get {
                return ResourceManager.GetString("SabreCustomBrackets_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;//version&quot;: &quot;05/07/2018&quot;},
        ///{
        ///&quot;HEXMinArmBaseDiam&quot;:4,
        ///&quot;HEXMaxArmBaseDiam&quot;:5.25,
        ///&quot;ArmType&quot;:&quot;Common&quot;,
        ///&quot;STDMinArmBaseDiam&quot;:4,
        ///&quot;STDMaxArmBaseDiam&quot;:5.25,
        ///&quot;ArmType&quot;:&quot;Common&quot;,
        ///&quot;STDMaxArmThick&quot;:0.1875,
        ///&quot;BracketID&quot;:&quot;YK07-LX&quot;,
        ///&quot;BracketThick&quot;:0.625,
        ///&quot;BracketOpening&quot;:7.125,
        ///&quot;ThruPlateSGLID&quot;:&quot;TP07-LX1&quot;,
        ///&quot;ThruPlateDBLID&quot;:&quot;TP07-LX2&quot;,
        ///&quot;ThruPlateThick&quot;:0.625,
        ///&quot;ThruPlateWidth&quot;:7,
        ///&quot;Height&quot;:9,
        ///&quot;MinEdgeDist&quot;:1.5,
        ///&quot;StiffenerQty&quot;:0,
        ///&quot;StiffenerThick&quot;:0,
        ///&quot;StiffenerWidth&quot;:0,
        ///&quot;StiffenerVertSpacing&quot;:0,
        ///&quot;BoltQty&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SabreFWTStdBrackets_json {
            get {
                return ResourceManager.GetString("SabreFWTStdBrackets_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [
        ///      {
        ///        &quot;FinishType&quot;: &quot;Galvanized&quot;,
        ///        &quot;MaterialThickness&quot;: &quot;.625&quot;
        ///      },
        ///      {
        ///        &quot;FinishType&quot;: &quot;Galvanized&quot;,
        ///        &quot;MaterialThickness&quot;: &quot;.75&quot;
        ///      },
        ///      {
        ///        &quot;FinishType&quot;: &quot;Galvanized&quot;,
        ///        &quot;MaterialThickness&quot;: &quot;1.00&quot;
        ///      },
        ///      {
        ///        &quot;FinishType&quot;: &quot;Galvanized&quot;,
        ///        &quot;MaterialThickness&quot;: &quot;1.25&quot;
        ///      },
        ///      {
        ///        &quot;FinishType&quot;: &quot;Galvanized&quot;,
        ///        &quot;MaterialThickness&quot;: &quot;1.50&quot;
        ///      },
        ///      {
        ///        &quot;FinishType&quot;: &quot;Galvanized&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaddleBracketMaterial_json {
            get {
                return ResourceManager.GetString("SaddleBracketMaterial_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{Id: &quot;4F&quot;,
        ///SideCount: 4,
        ///TubeOrientation: 0,
        ///Description: &quot;Square Tubing-Flat To Zero&quot;,
        ///IsTubing: true,
        ///IsRegularPolygon: true,
        ///UseFWTBracketTable: false
        ///},
        ///{Id: &quot;4T&quot;,
        ///SideCount: 4,
        ///TubeOrientation: 1,
        ///Description: &quot;Square Tubing-Point To Zero&quot;,
        ///IsTubing: true,
        ///IsRegularPolygon: true,
        ///UseFWTBracketTable: false
        ///},
        ///{Id: &quot;6F&quot;,
        ///SideCount: 6,
        ///TubeOrientation: 0,
        ///Description: &quot;Hexagonal-Flat To Zero&quot;,
        ///IsTubing: false,
        ///IsRegularPolygon: true,
        ///UseFWTBracketTable: false 
        ///},
        ///{Id: &quot;6T&quot;,
        ///Sid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SteelShapes_json {
            get {
                return ResourceManager.GetString("SteelShapes_json", resourceCulture);
            }
        }
    }
}
