//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialsLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialsLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;IDX&quot;: &quot;1&quot;,
        ///	&quot;Grade&quot;: &quot;1&quot;,
        ///	&quot;MaterialSpecification&quot;: &quot;A307-36&quot;,
        ///	&quot;Diameter&quot;: &quot;7.500000000000000e-001&quot;,
        ///	&quot;GrossArea&quot;: &quot;4.420000000000000e-001&quot;,
        ///	&quot;TensileArea&quot;: &quot;3.340000000000000e-001&quot;,
        ///	&quot;RootArea&quot;: &quot;3.020000000000000e-001&quot;,
        ///	&quot;ThreadCountPerInch&quot;: &quot;1.000000000000000e+001&quot;,
        ///	&quot;MinimumBoltSpacing&quot;: &quot;2.000000000000000e+000&quot;,
        ///	&quot;MinimumEdgeDistance&quot;: &quot;1.125000000000000e+000&quot;,
        ///	&quot;NutPointWidth&quot;: &quot;1.437500000000000e+000&quot;,
        ///	&quot;FlatWasherDiameter&quot;: &quot;1.468000000000000e+000&quot;,
        ///	&quot;FlatWasherThickness&quot;: &quot;1.770 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnchorBolts_json {
            get {
                return ResourceManager.GetString("AnchorBolts_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///	&quot;IDX&quot;: &quot;1&quot;,
        ///	&quot;Thickness&quot;: &quot;0.375&quot;,
        ///	&quot;MaxBoltCircleDiameter&quot;: &quot;50.0&quot;,
        ///	&quot;Inactive&quot;: &quot;false&quot;
        ///},
        ///{
        ///	&quot;IDX&quot;: &quot;2&quot;,
        ///	&quot;Thickness&quot;: &quot;0.50&quot;,
        ///	&quot;MaxBoltCircleDiameter&quot;: &quot;65.0&quot;,
        ///	&quot;Inactive&quot;: &quot;false&quot;
        ///},
        ///{
        ///	&quot;IDX&quot;: &quot;3&quot;,
        ///	&quot;Thickness&quot;: &quot;0.625&quot;,
        ///	&quot;MaxBoltCircleDiameter&quot;: &quot;95.0&quot;,
        ///	&quot;Inactive&quot;: &quot;false&quot;
        ///},
        ///{
        ///	&quot;IDX&quot;: &quot;4&quot;,
        ///	&quot;Thickness&quot;: &quot;0.75&quot;,
        ///	&quot;MaxBoltCircleDiameter&quot;: &quot;95.0&quot;,
        ///	&quot;Inactive&quot;: &quot;false&quot;
        ///},
        ///{
        ///	&quot;IDX&quot;: &quot;5&quot;,
        ///	&quot;Thickness&quot;: &quot;1.0&quot;,
        ///	&quot;MaxBoltCircleDiameter&quot;: &quot;150.0&quot;,
        ///	&quot;Inactive&quot;: &quot;false&quot;
        ///}].
        /// </summary>
        internal static string AnchorBoltTemplateThickness_json {
            get {
                return ResourceManager.GetString("AnchorBoltTemplateThickness_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///
        ////*   
        ///
        ////* Fort Worth Tower standard anchor bolt cage template geometry */
        ///{
        ///	&quot;IDX&quot;: &quot;1&quot;,
        ///	&quot;CustomerCode&quot;: &quot;FWT_Std&quot;,
        ///	&quot;BoltCircleType&quot;: &quot;0&quot;,
        ///	&quot;TopTemplateThickness&quot;: &quot;0.375&quot;,
        ///	&quot;IntermediateTemplateThickness&quot;: &quot;0.375&quot;,
        ///	&quot;BottomTemplateThickness&quot;: &quot;0.375&quot;,
        ///	&quot;OdBoltCircleAdder&quot;: &quot;6&quot;,
        ///	&quot;OdBoltCircleFactor&quot;: &quot;1&quot;,
        ///	&quot;IdBoltCircleAdder&quot;: &quot;-8&quot;,
        ///	&quot;IdBoltCircleFactor&quot;: &quot;1&quot;,
        ///	&quot;MaxBoltCircleDiameter&quot;: &quot;60.0&quot;,
        ///	&quot;MaxBoltQty&quot;: &quot;28&quot;,
        ///	&quot;MaterialSpec&quot;: &quot;A36&quot;,
        ///	&quot;Inactive&quot;: &quot;false&quot;
        ///},
        ///{
        ///	&quot;IDX&quot;: &quot;2&quot;,
        ///	&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdAnchorBoltCageTemplateGeometry_json {
            get {
                return ResourceManager.GetString("StdAnchorBoltCageTemplateGeometry_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ASTM&quot;: &quot;A572&quot;,
        ///    &quot;FuPsi&quot;: 75000,
        ///    &quot;FyPsi&quot;: 50000,
        ///    &quot;Thickness&quot;: 1,
        ///    &quot;Inactive&quot;: 0
        ///  },
        ///  {
        ///    &quot;ASTM&quot;: &quot;A572&quot;,
        ///    &quot;FuPsi&quot;: 75000,
        ///    &quot;FyPsi&quot;: 50000,
        ///    &quot;Thickness&quot;: 1.25,
        ///    &quot;Inactive&quot;: 0
        ///  },
        ///  {
        ///    &quot;ASTM&quot;: &quot;A572&quot;,
        ///    &quot;FuPsi&quot;: 75000,
        ///    &quot;FyPsi&quot;: 50000,
        ///    &quot;Thickness&quot;: 1.5,
        ///    &quot;Inactive&quot;: 0
        ///  },
        ///  {
        ///    &quot;ASTM&quot;: &quot;A572&quot;,
        ///    &quot;FuPsi&quot;: 75000,
        ///    &quot;FyPsi&quot;: 50000,
        ///    &quot;Thickness&quot;: 1.75,
        ///    &quot;Inactive&quot;: 0
        ///  },
        ///  {
        ///    &quot;ASTM&quot;: &quot;A572&quot;,
        ///    &quot;FuPsi&quot;: 75000, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SteelPlate_json {
            get {
                return ResourceManager.GetString("SteelPlate_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{Id: &quot;4F&quot;,
        ///SideCount: 4,
        ///TubeOrientation: 0,
        ///Description: &quot;Tubing-Flat To Zero&quot;,
        ///IsTubing: true,
        ///IsRegularPolygon: true,
        ///UseFWTBracketTable: false
        ///},
        ///{Id: &quot;4T&quot;,
        ///SideCount: 4,
        ///TubeOrientation: 1,
        ///Description: &quot;Tubing-Point To Zero&quot;,
        ///IsTubing: true,
        ///IsRegularPolygon: true,
        ///UseFWTBracketTable: false
        ///},
        ///{Id: &quot;6F&quot;,
        ///SideCount: 6,
        ///TubeOrientation: 0,
        ///Description: &quot;Hexagonal-Flat To Zero&quot;,
        ///IsTubing: false,
        ///IsRegularPolygon: true,
        ///UseFWTBracketTable: false 
        ///},
        ///{Id: &quot;6T&quot;,
        ///SideCount: 6,
        ///Tu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SteelShapes_json {
            get {
                return ResourceManager.GetString("SteelShapes_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;Description&quot;:&quot;A-325 Gr.92&quot;,
        ///    &quot;MaterialSpecification&quot;:&quot;A325-92&quot;,
        ///    &quot;QtGradeName&quot;:&quot;A325&quot;,
        ///    &quot;Diameter&quot;:0.625,
        ///    &quot;NutHeight&quot;:0.625,
        ///    &quot;NutPointWidth&quot;:1.25,
        ///    &quot;NutWeight&quot;:0.119,
        ///    &quot;GrossArea&quot;:0.307,
        ///    &quot;TensileArea&quot;:0.226,
        ///    &quot;RootArea&quot;:0.202,
        ///    &quot;ThreadCountPerInch&quot;:11,
        ///    &quot;MinimumBoltSpacing&quot;:1.75,
        ///    &quot;MinimumEdgeDistance&quot;:1.5,
        ///    &quot;FlatWasherDiameter&quot;:1.3125,
        ///    &quot;FlatWasherThickness&quot;:0.177,
        ///    &quot;BoltHeadAndNutWeight&quot;:0.2,
        ///    &quot;BoltShaftWeightPerInch&quot;:0.087,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructuralBolts_json {
            get {
                return ResourceManager.GetString("StructuralBolts_json", resourceCulture);
            }
        }
    }
}
